# Generated by Django 6.0.1 on 2026-02-03 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_line_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="departure",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.station",
            ),
        ),
        migrations.AddConstraint(
            model_name="linestop",
            constraint=models.UniqueConstraint(
                fields=("line", "order"), name="unique_order_per_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="linestop",
            constraint=models.UniqueConstraint(
                fields=("line", "station"), name="unique_station_per_line"
            ),
        ),
    ]
